# Generated by Django 5.0.6 on 2024-05-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10)),
                ('grado', models.CharField(max_length=10)),
                ('identificacion', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Enfermero',
        ),
        migrations.RenameField(
            model_name='enfermero',
            old_name='grado',
            new_name='horario',
        ),
    ]
