# Generated by Django 5.0.6 on 2024-05-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHospital', '0002_paciente_rename_profesor_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('CARDIOLOGIA', 'Cardiología'), ('DERMATOLOGIA', 'Dermatología'), ('GASTROENTEROLOGIA', 'Gastroenterología'), ('GERIATRIA', 'Geriatría'), ('INMUNOLOGIA', 'Inmunología'), ('PEDIATRIA', 'Pediatría')], max_length=50),
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHospital.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHospital.paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
            },
        ),
    ]
