# Generated by Django 5.0.6 on 2024-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHospital', '0003_alter_doctor_especialidad_citamedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=50),
        ),
    ]
